<?php

require_once "config.php";
require_once "graphics.php";

session_start();

if (!isset($_SESSION['login']) || !($_SESSION['login'] === true)) {
    header("Location: login.php");
}

?>
<html>
<head>
<title>stats for <?php echo $hostname; ?> - sere</title>
<script src="sere.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="template.css">
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<h1>Stats for <span class="hostname"><?php echo $hostname; ?></span></h1>

<div class="container">

<?php

$g = new graphics($graphs,$iface);

$g->draw();

?>

</div>

<p style="text-align: center;"><span class="smallnote">Generated by <a href="https://github.com/linuxitux/sere">sere v0.1.2</a></span></p>

<script>
updateGraphics(null);
var loop = window.setInterval(updateMetrics,1000*<?php echo $update_interval; ?>);
</script>

</body>
