<?php

require_once "config.php";
require_once "graphics.php";
require_once "generatestatdata.php";
require_once "importstatfiledata.php";
require_once "buildjsonstructure.php";

session_start();

if (!isset($_SESSION['login']) || !($_SESSION['login'] === true)) {
    header("Location: login.php");
}

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title>Stats for <?php echo $hostname; ?></title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<script type="text/javascript" src="sysstatgraph.js"></script>
<script type="text/javascript" src="rendergraph.js"></script>
<script src="sere.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="template.css">
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<h1>Stats for <span class="hostname"><?php echo $hostname; ?></span></h1>
<h2><a class="buttons" href=".">LIVE</a>&nbsp;&#8226;&nbsp;<a class="buttons" href="?p=report">REPORT</a></h2>

<?php

if (isset($_GET["p"]) && $_GET["p"] == "report") {

    $generatestatdata = new generatestatdata();
    $generatestatdata->execute();

    ?>
    <div id="content"></div>

    <p style="text-align: center;"><span class="smallnote">Generated by <a href="http://magnetikonline.com/sysstatgraph/">SysStat Graph Version 0.4</a></span></p>

    <script type="text/javascript">
    sysstatgraph.statdata = <?php echo((is_file(JSONSTRUCTUREFILENAME)) ? file_get_contents(JSONSTRUCTUREFILENAME) : '{}'); ?>;
    sysstatgraph.init();
    </script>
    <?php

}
else {

    ?>
    <div class="container">
    <?php

    $g = new graphics($graphs,$iface);
    $g->draw();

    ?>
    </div>

    <p style="text-align: center;"><span class="smallnote">Generated by <a href="https://github.com/linuxitux/sere">sere v0.1.2</a></span></p>

    <script>
    updateGraphics(null);
    var loop = window.setInterval(updateMetrics,1000*<?php echo $update_interval; ?>);
    </script>
    <?php

}

?>

</body>
</html>
